### ISSUE TITLE
RDFS Type to @type property

### ISSUE THREAD

**Issue by awanczowski** [RDFLib/rdflib-jsonld#102]
I am trying to convert a turtle file that contains rdfs:type. I was wondering if it is possible to have the JSON-LD @type be used instead. 

Current Output: 
```
"http://www.w3.org/2000/01/rdf-schema#type": {
        "@id": "sport:Team"
 }

```

Desired Output: 
`"@type": "sport:Team"`

**Comment by awanczowski** [comment]
Adding the following to the context seems to work as expected. However, I'm not sure if it is good practice to overload the @type property. 

 ```
"@type": {
            "@id": "http://www.w3.org/2000/01/rdf-schema#type",
            "@type": "@id"
        }
```

**Comment by nicholascar** [comment]
Hmmmm... there is no property of RDFS `type` (`rdfs:type`), I think you mean RDF `type` (`rdf:type`). Try changing the property.

**Comment by awanczowski** [comment]
Thanks, I forgot to update the ticket. The samples I was given had the wrong namespace.
