### ISSUE TITLE
Can't serialize unicode characters properly

### ISSUE THREAD

**Issue by snowwolf007cn** [RDFLib/rdflib-jsonld#23]
Origin string:"一切事务的基类”
after serilizing: "\uxxxx\uxxxx\uxxx...."

need to serilize it in origin

Maybe I didn't find to right parameters to control it.
if there is one, thank for tell me it.

**Comment by lrowe** [comment]
By default Python's json module serializes as ASCII, so unicode characters get escaped. Perhaps try specifying ``encoding='utf-8'`` in serialize?
