### ISSUE TITLE
blank node id serialization lacks prefix

### ISSUE THREAD

**Issue by edsu** [RDFLib/rdflib-jsonld#28]
I've noticed a problem with Blank Node serialization when a context is included. Here's an example that should demonstrate it:

``` python

from rdflib import URIRef, BNode, Literal, ConjunctiveGraph, RDFS
from rdflib.plugin import register, Serializer

register( 'json-ld', Serializer, 'rdflib_jsonld.serializer', 'JsonLDSerializer')

g = ConjunctiveGraph()
b = BNode()

g.add((URIRef('http://example.com'), URIRef('http://example.com/ns/has'), b))
g.add((b, RDFS.label, Literal('foo')))

context = {
    "has": {
        "@type": "@id",
        "@id": "http://example.com/ns/has"
    }
}

print g.serialize(format="json-ld", context=context)
```

When you run this, you get this output, where the Blank Node identifier lacks the `_:` prefix, and the label assertion is lost?

``` javascript
{
  "@context": {
    "has": {
      "@id": "http://example.com/ns/has",
      "@type": "@id"
    }
  },
  "@id": "http://example.com",
  "has": "N048ab6e6426448408ee34e29e8c38602"
}
```

**Comment by raedtjr** [comment]
i am facing the same issue! could you please let me know what should I do to solve this problem ? since it is not mentioned here

**Comment by joernhees** [comment]
[![xkcd wisdom of the ancients](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)](http://xkcd.com/979/)

which versions of rdflib and rdflib-jsonld are you using @raedtjr ?

**Comment by raedtjr** [comment]
Thank you alot for your answer, i am stuck at this for one week trying to figure out a solution.
My rdflib version is :  4.2.1. Regarding the rdflib-jsonld can you let me know how to check its version ?

**Comment by raedtjr** [comment]
cool picture btw it really describes my deep feelings hahah :D

**Comment by joernhees** [comment]
> Regarding the rdflib-jsonld can you let me know how to check its version ?

either use `pip list` and search for rdflib in it (e.g., `pip list | grep rdflib`) or use the following in python:
```python
import rdflib_jsonld
print(rdflib_jsonld.__version__)
```

**Comment by raedtjr** [comment]
So the Jsonld version is 0.3.
I would really appreciate it if you can provide me with a solution because this is a really important part of my project.

**Comment by joernhees** [comment]
well, i'd first suggest to try and update to the latest release...
for example with `pip install -U rdflib-jsonld`
