### ISSUE TITLE
default graph is not handled correctly

### ISSUE THREAD

**Issue by pchampin** [RDFLib/rdflib-jsonld#34]
According to the [JSON-LD specification](http://www.w3.org/TR/json-ld/#named-graphs):

>

    When a JSON-LD document's top-level structure is an object that contains no other properties than @graph and optionally @context (properties that are not mapped to an IRI or a keyword are ignored), @graph is considered to express the otherwise implicit default graph.

Still, when parsing a JSON-LD file with a default graph into a ConjunctiveGraph,
I end up with the ``default_context`` of that ConjunctiveGraph being empty,
and the triples of the default graph stored in another context, identified with a blank node...

Example in the following code:
```python
from StringIO import StringIO
from rdflib import ConjunctiveGraph
from rdflib.plugin import register, Parser
register('application/ld+json', Parser, 'rdflib_jsonld.parser', 'JsonLDParser')

f = StringIO("""
{
    "@context": "http://schema.org/",
    "@graph": [
        { "@id": "http://example.org/data#jdoe",
          "name": "John"
        },
        { "@id": "http://example.org/data#janedoe",
          "name": "Jane"
        },
        { "@id": "http://example.org/data#metadata",
          "@graph": [
              { "@id": "http://example.org/data",
                "creator": "http://example.org/data#janedoe"
              }
          ]
        }
    ]
}
""")

cg = ConjunctiveGraph()
cg.parse(f, format="application/ld+json")
print "conjunctive graph contains %s triples" % len(cg)
print "default graph contains %s triples (expected 2)" % len(cg.default_context)
for i in cg.contexts():
    print "other graph in cg (%s) contains %s triples" % (i.identifier, len(i))
```

**Comment by niklasl** [comment]
This issue is dependent on RDFLib/rdflib#436. What you need here should possible by using the latest sources of rdflib and rdflib-jsonld and changing your parse invocation to:

```python
cg.default_context.parse(f, format="application/ld+json")
```

If that works for you, can we close this specific case?

**Comment by pchampin** [comment]
Your trick works (although I had to install rdflib and rdlib-jsonld from github rather than pypi). I agree to close this issue, as it is indeed a consequence of RDFLib/rdflib#436 .

**Comment by danbri** [comment]
I can't see a default_context field on my Graph or ConjunctiveGraph objects (rdflib 4.2.2); has the API changed?
