### ISSUE TITLE
Serialized  @type info if it is present 

### ISSUE THREAD

**Issue by cardinal27513** [RDFLib/rdflib-jsonld#4]
See that if type is one of 
```python
PLAIN_LITERAL_TYPES = set([XSD.integer, XSD.float, XSD.double, XSD.decimal,
        XSD.boolean, XSD.string])
```

They are skipped in the serialization process.  Any good reason for that?
It gives me issue in my case, since I rely on the serialized data and after further processed, will create new RDF graph.. without the type info, the parser won’t be able to tell what type the data is and next time when serialized, won’t have the type info.
Right now I comment it out and force it to serialize all type info as long as it is present. That is more consistent,,'

**Comment by niklasl** [comment]
I believe this behaviour now properly supports round-tripping. (It can also be controlled by the `use_native_types` parameter to `serialize` when no context is given (i.e. when producing expanded JSON-LD, for which it is `False` by default).)
