### ISSUE TITLE
Is there a plan to create a new PyPI release?

### ISSUE THREAD

**Issue by gklyne** [RDFLib/rdflib-jsonld#41]
I'm keen to start using the updates created for issue #33 in my software, but for installation I need to be able to install dependencies from PyPI.

I could create a private copy and use that, but gratuitous forking of the in-use codebase seems not the best thing to be doing here.

**Comment by niklasl** [comment]
I'm on travel with limited resources right now, but I think I can make time this weekend to cut a release.

**Comment by gklyne** [comment]
That would be great (but don't sweat it at the expense of your personal life) - I'm hoping to push out a new release of my software, whose test suite depends on fixes in 0.4, later next week.

Thanks!

**Comment by niklasl** [comment]
No problem, this was really overdue. I just cut a 0.4.0 release.
