### ISSUE TITLE
Fails with "http://schema.org/" context

### ISSUE THREAD

**Issue by mih** [RDFLib/rdflib-jsonld#42]
Using this toy json-ld from the playground the following code fails:

```
>>> from rdflib import Graph
>>> test_json="""
... {
...   "@context": "http://schema.org/",
...   "@type": "Person",
...   "name": "Jane Doe",
...   "jobTitle": "Professor",
...   "telephone": "(425) 123-4567",
...   "url": "http://www.janedoe.com"
... }"""
>>> Graph().parse(data=test_json, format='json-ld')
<snip long traceback>
ValueError: No JSON object could be decoded
```

This culprit seems to be that the schema.org context cannot be obtained properly.

```
>>> from rdflib_jsonld.util import source_to_json
>>> source_to_json("http://schema.org/")
ValueError: No JSON object could be decoded
```

which seems to be the "fault" of the corresponding function from rdflib

```
>>> from rdflib.parser import create_input_source
>>> create_input_source("http://schema.org/").getByteStream().read()[:50]
'<!DOCTYPE html>\n<html xmlns="http://www.w3.org/199'
```

It yields the html variant of that page, whereas it should likely do something like this:
https://github.com/digitalbazaar/pyld/blob/master/lib/pyld/jsonld.py#L385
and request 'application/json'  from the server.

Apologies if that assessment is wrong. I decided to report it here and not against rdflib, as this issues seems to be json-focused (not RDF) and schema.org looks like a relevant component of the jsonld ecosystem.

**Comment by zimeon** [comment]
@mih - I think the problem is simply that you are using the wrong URI for the schema.org context. Per https://schema.org/docs/howwework.html it should be https://schema.org/docs/jsonldcontext.json . With this in place your example works:

```
>>> from rdflib import Graph
INFO:rdflib:RDFLib Version: 4.2.1
>>> test_json = """
... {
...   "@context": "https://schema.org/docs/jsonldcontext.json",
...   "@type": "Person",
...   "name": "Jane Doe",
...   "jobTitle": "Professor",
...   "telephone": "(425) 123-4567",
...   "url": "http://www.janedoe.com"
... }"""
>>> g = Graph().parse(data=test_json, format='json-ld')
>>> print(g.serialize(format="nt").decode('utf-8'))
_:Nbe6149bb453a44afb7e83a8ae4328026 <http://schema.org/jobTitle> "Professor" .
_:Nbe6149bb453a44afb7e83a8ae4328026 <http://schema.org/telephone> "(425) 123-4567" .
_:Nbe6149bb453a44afb7e83a8ae4328026 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Person> .
_:Nbe6149bb453a44afb7e83a8ae4328026 <http://schema.org/name> "Jane Doe" .
_:Nbe6149bb453a44afb7e83a8ae4328026 <http://schema.org/url> <http://www.janedoe.com/> .
```

**Comment by mih** [comment]
@zimeon Thanks for your feedback. Just to be clear: It is not "me" doing it wrong. It would be json-ld.org:

http://json-ld.org/playground (click on "Person")

In any case, I can retrieve the content you are referring with the appropriate request:

````
curl -i -L -H "Accept: application/ld+json" "http://schema.org"
````

So the URL is fine in general. I suspect that the HTTP request issued by rdflib-jsonld retrieves the HTML and not the JSON, but I haven't dug into the code. So this is speculation.

**Comment by zimeon** [comment]
@mih - My apologies, I had not noticed the conneg support from `https://schema.org/` and thus had not understood that the problem properly.

However, now I check I don't find the problem at all with rdflib (4.2.1) & rdflib-jsonld (0.4.0), your original example works fine for me, or the following simplified version:

```
>>> test_json = """{"@context": "https://schema.org/", "@type": "Person", "name": "Jane Doe" }"""
>>> g = Graph().parse(data=test_json, format='json-ld')
>>> print(g.serialize(format="nt").decode('utf-8'))
_:N9a86040aa99a471b9a00e1a09091d1e8 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Person> .
_:N9a86040aa99a471b9a00e1a09091d1e8 <http://schema.org/name> "Jane Doe" .
```

Using the following as a testserver:

```
# Show headers for incoming GET request
# see https://docs.python.org/3/library/http.server.html
import http.server
import socketserver

class Handler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        print(self.headers)

address = ('', 8000)
httpd = socketserver.TCPServer(address, Handler)
print("Listening at", address, '...')
httpd.serve_forever()
```

I see the following headers:

```
Accept-Encoding: identity
Host: localhost:8000
Connection: close
User-Agent: rdflib-4.2.1 (http://rdflib.net/; eikeon@eikeon.com)
Accept: application/ld+json, application/json;p=0.9, */*;q=0.1
```

for an incoming request generated with 

```
>>> from rdflib import Graph
INFO:rdflib:RDFLib Version: 4.2.1
>>> test_json = """{"@context": "http://localhost:8000/", "@type": "Person", "name": "Jane Doe" }"""
>>> g = Graph().parse(data=test_json, format='json-ld')
```

and a request

```
curl -i -L -H "Accept: application/ld+json, application/json;p=0.9, */*;q=0.1" "http://schema.org"
```

returns JSON-LD as expected. Perhaps some difference in versions somewhere?

**Comment by mih** [comment]
@zimeon Thanks for the investigation! I can confirm that this is a version issue. Your code fails in the exact same way that I reported on Debian's python-rdlib package version 4.1.2-3 (the latest available one), with the python-rdflib-jsonld package version 0.4.0-1 also being installed from Debian's repository.

After upgrading rdlib to 4.2.1 (your test version) via pip, but keeping Debian's version of 0.4.0, I can replicate the correct behavior that you reported.

I will file a bug report in Debian's BTS.

Thanks again!

**Comment by mih** [comment]
http://bugs.debian.org/843397

**Comment by danbri** [comment]
Is this still a problem?

**Comment by mih** [comment]
No, it seems not. Debian had the fix in Dec 2016.
