### ISSUE TITLE
Parser needs to support  "@graph" at the top level that is the new syntax... 

### ISSUE THREAD

**Issue by cardinal27513** [RDFLib/rdflib-jsonld#5]
See the serializer issues
https://github.com/RDFLib/rdflib-jsonld/issues/2

**Comment by arodbar** [comment]
I'm trying to parse a Json-ld data that has the the tag "@graph" and the parser doesn't read it. The example which I'm trying to parse is  
```
 "@context": {},
  "@id":"http://example.com/graph/1",
  "@graph": [
       {
          "@id": "http://example.com/node/1",
          "http://example.com/property": [ { "@value": "property" } ]
       }
  ]
}
```

**Comment by niklasl** [comment]
This should work. If you're still having this problem, which version of rdflib-jsonld are you using and how is the invocation done?

**Comment by militarpancho** [comment]
I have the same problem parsing a json-ld data with @graph. My rdflib-jsonld is the one which is in the Pypi. The invocation to parse: `g= Graph().parse(data=file.read(), format='json-ld')` and to serialize: `g.serialize(format='n3', indent='4'). `

**Comment by niklasl** [comment]
See if it works if you change the code to:

    g = ConjunctiveGraph()
    g.parse(...)
