### ISSUE TITLE
TypeError when parsing context with @version tag

### ISSUE THREAD

**Issue by missinglinks** [RDFLib/rdflib-jsonld#54]
Parsing a json-ld file with the '@version' tag in the context results in an TypeError:

`274     def _prep_expand(self, expr):`
`--> 275         if ':' not in expr:`
` 276             return True, None, expr`
` 277         pfx, local = expr.split(':', 1)`
`TypeError: argument of type 'float' is not iterable`

Used context file: https://linked.art/ns/v1/linked-art.json

**Comment by azaroth42** [comment]
This does work with PyLD: https://github.com/digitalbazaar/pyld 
PyLD also supports framing (re long outstanding #17)
@missinglinks: please let me know if you'd like to join the linked.art slack or anything :) We'd love to know what you're doing, and help out!

**Comment by RinkeHoekstra** [comment]
Just curious as to the status of this issue. It is essentially a bug in the current `context.py` where it expects to always see a string for a JSON value, whereas the `@version` key (and indeed other attributes as well) is supposed to be a number according to the specs at https://www.w3.org/TR/json-ld11/#json-ld-1-1-processing-mode

**Comment by azaroth42** [comment]
JSON-LD 1.1 is nearing completion in terms of editing and features, so it would be a good time to start working on implementation! :)

**Comment by sanuann** [comment]
Is this issue resolved? I am still getting the same error when parsing context with `@version` tag.

**Comment by niklasl** [comment]
I just fixed this particular "tripping on strings in context" bug in 9a6d837c8e141.

(I'm having a hard time finding time to work on JSON-LD 1.1 feature alas.)

**Comment by niklasl** [comment]
I'm putting some effort into making rdflib-jsonld (mainly the parser) handle at least the main features of JSON-LD 1.1. You can see the state of that in #74. There's also a discussion about maintenance and an upcoming release in #68.

With that in mind, can we consider this specific issue fixed?

**Comment by sanuann** [comment]
@niklasl I don't think so it's fixed. I used the `pyld` library to convert my json-ld data to turtle format and then use PySHACL to validate them.

**Comment by niklasl** [comment]
@sanuann that's fair!

The parser doesn't trip on `@version` now (on master); more 1.1 support is at #74. Closing this.
